### ISSUE TITLE
Typo in README

### ISSUE THREAD

**Issue by ronibarylkoD** [thebongy/version-check#3]
I think there is a typo in README.md

```yaml
on:
  pull_request:
    branches:
      - staging
name: Continuous integration
jobs:
  version-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: git fetch --all --tags

      - name: Check Release Version
        uses: thebongy/version-check@v1
        with:
          file: package.json
          tagFormat: v${version}-beta
        id: version_check_staging
      - name:
        run: |
        echo "Version ${{steps.version_check.outputs.releaseVersion}}"
```

When it runs ```echo "Version ${{steps.version_check.outputs.releaseVersion}}"``` it should say  ```echo "Version ${{steps.version_check_staging.outputs.releaseVersion}}"```, using step id. Perhaps it is a stupid detail, but I am noob using github actions and it gave me a headache for an hour!
